apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kdavis-app-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "kdavis/app/config"
        objectType: "secretsmanager"
        jmesPath:
          - path: APP_ENV
            objectAlias: APP_ENV
          - path: APP_KEY
            objectAlias: APP_KEY
  secretObjects:
    - secretName: kdavis-app-secret
      type: Opaque
      data:
        - objectName: APP_ENV
          key: APP_ENV
        - objectName: APP_KEY
          key: APP_KEY
